### ISSUE TITLE
failing to test on ubuntu-14.04 from head of master

### ISSUE THREAD

**Issue by schwehr** [schwehr/libais#130]
https://github.com/schwehr/libais/commit/170b2145ddf9c0d534af8ccedac7b5a5059bf485

    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/libais/ais27.cpp -o build/temp.linux-x86_64-2.7/src/libais/ais27.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    creating build/lib.linux-x86_64-2.7
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/libais/ais_py.o build/temp.linux-x86_64-2.7/src/libais/ais.o build/temp.linux-x86_64-2.7/src/libais/ais1_2_3.o build/temp.linux-x86_64-2.7/src/libais/ais4_11.o build/temp.linux-x86_64-2.7/src/libais/ais5.o build/temp.linux-x86_64-2.7/src/libais/ais6.o build/temp.linux-x86_64-2.7/src/libais/ais7_13.o build/temp.linux-x86_64-2.7/src/libais/ais8.o build/temp.linux-x86_64-2.7/src/libais/ais8_1_22.o build/temp.linux-x86_64-2.7/src/libais/ais8_1_26.o build/temp.linux-x86_64-2.7/src/libais/ais8_200.o build/temp.linux-x86_64-2.7/src/libais/ais8_366.o build/temp.linux-x86_64-2.7/src/libais/ais8_367.o build/temp.linux-x86_64-2.7/src/libais/ais9.o build/temp.linux-x86_64-2.7/src/libais/ais10.o build/temp.linux-x86_64-2.7/src/libais/ais12.o build/temp.linux-x86_64-2.7/src/libais/ais14.o build/temp.linux-x86_64-2.7/src/libais/ais15.o build/temp.linux-x86_64-2.7/src/libais/ais16.o build/temp.linux-x86_64-2.7/src/libais/ais17.o build/temp.linux-x86_64-2.7/src/libais/ais18.o build/temp.linux-x86_64-2.7/src/libais/ais19.o build/temp.linux-x86_64-2.7/src/libais/ais20.o build/temp.linux-x86_64-2.7/src/libais/ais21.o build/temp.linux-x86_64-2.7/src/libais/ais22.o build/temp.linux-x86_64-2.7/src/libais/ais23.o build/temp.linux-x86_64-2.7/src/libais/ais24.o build/temp.linux-x86_64-2.7/src/libais/ais25.o build/temp.linux-x86_64-2.7/src/libais/ais26.o build/temp.linux-x86_64-2.7/src/libais/ais27.o -o build/lib.linux-x86_64-2.7/_ais.so
    copying build/lib.linux-x86_64-2.7/_ais.so -> 
    Traceback (most recent call last):
      File "setup.py", line 111, in <module>
        test_suite="test"
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/schwehr/src/libais-2/ve/local/lib/python2.7/site-packages/setuptools/command/test.py", line 138, in run
        self.with_project_on_sys_path(self.run_tests)
      File "/home/schwehr/src/libais-2/ve/local/lib/python2.7/site-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
        func()
      File "/home/schwehr/src/libais-2/ve/local/lib/python2.7/site-packages/setuptools/command/test.py", line 164, in run_tests
        testLoader = cks
      File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
        self.parseArgs(argv)
      File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
        self.createTests()
      File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
        self.module)
      File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
        suites = [self.loadTestsFromName(name, module) for name in names]
      File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
        return self.loadTestsFromModule(obj)
      File "/home/schwehr/src/libais-2/ve/local/lib/python2.7/site-packages/setuptools/command/test.py", line 35, in loadTestsFromModule
        tests.append(self.loadTestsFromName(submodule))
      File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
        parent, obj = obj, getattr(obj, part)
    AttributeError: 'module' object has no attribute 'nmea_queue_test'

**Comment by schwehr** [comment]
Ideas for improving the README.rst:

https://github.com/geowurster/newlinejson#installing
