### ISSUE TITLE
Usage example in readme throws DecodeError

### ISSUE THREAD

**Issue by anitagraser** [schwehr/libais#92]
The example 

```
import ais
ais.decode('55NBjP01mtGIL@CW;SM<D60P5Ld000000000000P0`<3557l0<50@kk@K5h@00000000000', 0)
```

throws 

```
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
     execfile(filename, namespace)
   File "/home/agraser/temp/ais/decode_some_ais.py", line 60, in <module>
     print ais.decode('55NBjP01mtGIL@CW;SM<D60P5Ld000000000000P0`<3557l0<50@kk@K5h@00000000000', 0)
 _ais.DecodeError: Ais5: AIS_ERR_BAD_BIT_COUNT
```

using libais-0.15-py2.7-linux-x86_64.egg

**Comment by anitagraser** [comment]
Is this expected to happen or is this unintentional?
